version: '3'

networks:
  default:
    external:
      name: latelier

services:
  tableau-server:
    image: tableau-server
    container_name: tableau-server
    hostname: tableau-server
    volumes:
      - ./data:/var/opt/tableau
      - ./etc/opt:/etc/opt
      # - ./etc/systemd/system:/etc/systemd/system
      - ./config:/opt/tableau/docker_build/
      - ./run:/run
      - ./log:/var/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      TSM_PASSWORD: ${TSM_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8080:80"
      - "8850:8850"
    privileged: true
    
