version: '2'

networks:
  default:
    external:
      name: latelier

services:
  tableau-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        proxy: ${http_proxy}
        TABLEAU_VERSION: ${TABLEAU_VERSION}
    image: tableau-server
    container_name: tableau-server
    volumes:
      - ./data:/var/opt/tableau
      - ./etc/opt:/etc/opt
      - ./etc/systemd/system:/etc/systemd/system
      - ./config:/opt/tableau/docker_build/
      - ./run:/run
      - ./log:/var/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "8080:80"
      - "8085:8085"
    privileged: true
    
